# /etc/nixos/.sops.yaml
keys:
  - &nixos_server age1v3zhmfjf6sda8pcqss5q83q02lt9megk70zs0pptm28usekykess5uqmuz

creation_rules:
  - path_regex: ^secrets/.*\.(yaml|txt)$
    key_groups:
      - age:
          - *nixos_server
